### ISSUE TITLE
Error in ray-tune 

### ISSUE THREAD

**Issue by yeounyi** [huggingface/blog#106]
Thanks for great blog posts!
I was reading [this post](https://huggingface.co/blog/ray-tune) and faced some errors while integrating ray and huggingface transformers. 
It seems `n_jobs`, `n_samples` in `hyperparameter_search` function doesn't exist anymore.
Even removing these two arguments, I still get `TypeError: can't pickle _thread.RLock objects`.
Can you help me on that? Thanks 

```
Traceback (most recent call last):
  File "mask_ins.py", line 237, in <module>
    backend="ray",)
  File "/home/yeoun/.local/lib/python3.6/site-packages/transformers/trainer.py", line 1459, in hyperparameter_search
    best_run = run_hp_search(self, n_trials, direction, **kwargs)
  File "/home/yeoun/.local/lib/python3.6/site-packages/transformers/integrations.py", line 235, in run_hp_search_ray
    **kwargs,
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 297, in run
    _ray_auto_init()
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/tune/tune.py", line 664, in _ray_auto_init
    ray.init()
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/worker.py", line 771, in init
    hook()
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/tune/registry.py", line 171, in flush
    self.references[k] = ray.put(v)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/worker.py", line 1514, in put
    object_ref = worker.put_object(value)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/worker.py", line 261, in put_object
    serialized_value = self.get_serialization_context().serialize(value)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/serialization.py", line 324, in serialize
    return self._serialize_to_msgpack(value)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/serialization.py", line 304, in _serialize_to_msgpack
    self._serialize_to_pickle5(metadata, python_objects)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/serialization.py", line 264, in _serialize_to_pickle5
    raise e
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/serialization.py", line 261, in _serialize_to_pickle5
    value, protocol=5, buffer_callback=writer.buffer_callback)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/yeoun/.local/lib/python3.6/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 580, in dump
    return Pickler.dump(self, obj)
TypeError: can't pickle _thread.RLock objects
```

**Comment by dmilcevski** [comment]
I am facing the same issue. Is there fix for this issue?

**Comment by richardliaw** [comment]
let's move discussion to https://github.com/huggingface/transformers/issues/11249 ?

**Comment by amogkam** [comment]
If you disable the memory tracker (pass in `skip_memory_metrics=True` into your `TrainingArguments`) then you will no longer get the pickling error.

In the next transformers release, `skip_memory_metrics` will default to `True`, and even if it is explicitly set to False, it will automatically be disabled if you are using Ray Tune for HPO.

**Comment by dynamicwebpaige** [comment]
👋 Greetings! 

Am compiling a list of Ray-affiliate issues and feature requests in Hugging Face organization repos. Would the pull request `Yard1` and @richardliaw mentioned resolve this issue, or is there still work to be done to ensure that mitigate the `ImportError` with Ray Tune?

cc: @LysandreJik

**Comment by amogkam** [comment]
@dynamicwebpaige this should be resolved by https://github.com/huggingface/transformers/pull/12134, and this issue is the same as the one that @richardliaw linked (https://github.com/huggingface/transformers/issues/11249)
