### ISSUE TITLE
(fine-tune-wav2vec2-english.md) AssertionError: No inf checks were recorded for this optimizer

### ISSUE THREAD

**Issue by xzwworkplace** [huggingface/blog#143]
Hi
**@patrickvonplaten**
I encountered some error while following this blog to fine tune a Chinese dataset.
After I solved the last problem (RuntimeError：element 0 of tensor does not require grad and does not have a grad_fn),
I encountered this problem,as follows:
I don't know how to solve it

> Traceback (most recent call last):
  File "/media/xzw/WORK/fairseq/work/3.py", line 220, in <module>
    trainer.train()
  File "/home/xzw/anaconda3/envs/work/lib/python3.7/site-packages/transformers/trainer.py", line 1092, in train
    self.scaler.step(self.optimizer)
  File "/home/xzw/anaconda3/envs/work/lib/python3.7/site-packages/torch/cuda/amp/grad_scaler.py", line 318, in step
    assert len(optimizer_state["found_inf_per_device"]) > 0, "No inf checks were recorded for this optimizer."
AssertionError: No inf checks were recorded for this optimizer.
  0%|          | 0/112620 [00:02<?, ?it/s]

Best regards
xiao

**Comment by patrickvonplaten** [comment]
Hey @xzwworkplace,

Could you try to provide a google colab that would allow me to reproduce the error? :-)
