### ISSUE TITLE
gemma: jax/ flax version

### ISSUE THREAD

**Issue by Ruturaj4** [huggingface/blog#1844]
I get following error when I try to run Gemma model:

```
Traceback (most recent call last):
  File "/home/ruvaidya/hf/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 266, in __getattr__
    return self.data[item]
KeyError: 'shape'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gemma_jax.py", line 17, in <module>
    output = model.generate(inputs, params=params, max_new_tokens=20, do_sample=False)
  File "/home/ruvaidya/hf/lib/python3.8/site-packages/transformers/generation/flax_utils.py", line 366, in generate
    batch_size = input_ids.shape[0]
  File "/home/ruvaidya/hf/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 268, in __getattr__
    raise AttributeError
AttributeError
```

are there any specific jax/ flax versions?

source:
```Python
import jax.numpy as jnp
from transformers import AutoTokenizer, FlaxGemmaForCausalLM

model_id = "google/gemma-2b"

tokenizer = AutoTokenizer.from_pretrained(model_id)
tokenizer.padding_side = "left"

model, params = FlaxGemmaForCausalLM.from_pretrained(
        model_id,
        dtype=jnp.bfloat16,
        revision="flax",
        _do_init=False,
)

inputs = tokenizer("Valencia and Málaga are", return_tensors="np", padding=True)
output = model.generate(inputs, params=params, max_new_tokens=20, do_sample=False)
output_text = tokenizer.batch_decode(output.sequences, skip_special_tokens=True)
```

**Comment by sanchit-gandhi** [comment]
Currently, you're passing a dictionary of `{input_ids, attention_mask}` to the `.generate` method. You either need to specify the `input_ids`:
```diff
- output = model.generate(inputs, params=params, max_new_tokens=20, do_sample=False)
+ output = model.generate(input_ids=inputs.input_ids, params=params, max_new_tokens=20, do_sample=False)
```

Or pass it as named kwargs:
```diff
- output = model.generate(inputs, params=params, max_new_tokens=20, do_sample=False)
+ output = model.generate(**inputs, params=params, max_new_tokens=20, do_sample=False)
```

If you have batched inputs, you'll need to pass the attention mask to get correct outputs. So your safest option is the second one.

**Comment by pcuenca** [comment]
Thank you @sanchit-gandhi!
