### ISSUE TITLE
KeyError in processor.batch_decode

### ISSUE THREAD

**Issue by gfigueroa** [huggingface/blog#210]
Hi @patrickvonplaten,

Thank you for your latest blogpost on boosting Wav2Vec2 with n-grams. I'm having trouble there with the `processor.batch_decode` step, since I get a `KeyError` in the `pyctcdecode/decoder.py` module when running the `Wav2Vec2ProcessorWithLM` model and processor.

I am using python 3.8.2, `pyctcdecode==0.3.0`, and `transformers==4.15.0`.

Below is the traceback:

```
Traceback (most recent call last):
  File "/Users/gfigueroa/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/gfigueroa/.pyenv/versions/3.8.2/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/gfigueroa/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pyctcdecode/decoder.py", line 547, in _decode_beams_mp_safe
    decoded_beams = self.decode_beams(
  File "/Users/gfigueroa/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pyctcdecode/decoder.py", line 525, in decode_beams
    decoded_beams = self._decode_logits(
  File "/Users/gfigueroa/.pyenv/versions/3.8.2/lib/python3.8/site-packages/pyctcdecode/decoder.py", line 329, in _decode_logits
    language_model = BeamSearchDecoderCTC.model_container[self._model_key]
KeyError: b'\xab\x94\xb9\xb0I\xc0\x1b\xf93\xa9\xa6\x1c]\t\xf6\x86'
```

**Comment by gfigueroa** [comment]
Being checked also at https://github.com/kensho-technologies/pyctcdecode/issues/41.

**Comment by patrickvonplaten** [comment]
I think it has been solved in [kensho-technologies/pyctcdecode#41 ](https://github.com/kensho-technologies/pyctcdecode/issues/41) no? :-)

**Comment by gfigueroa** [comment]
Partially, yes. It works with
```
transcription = processor.decode(logits.numpy()[0]).text
```
but not with the original line in the blog using `batch_decode`
```
transcription = processor.batch_decode(logits.numpy()).text
```
