### ISSUE TITLE
processor = AutoProcessor.from_pretrained("patrickvonplaten/wav2vec2-base-100h-with-lm") timesout

### ISSUE THREAD

**Issue by edmond-toch** [huggingface/blog#384]
I've tried a few times to run this command:
processor = AutoProcessor.from_pretrained("patrickvonplaten/wav2vec2-base-100h-with-lm")
on a macbook pro (Mac OS Monterey 12.4 with M1 chip).
I do have slow internet connection, but the command stops when downloading at about 2.15GB out of 3.12GB.
The (last line of the) error is:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.

I've found the following link: https://huggingface.co/patrickvonplaten/wav2vec2-base-100h-with-lm/blob/main/language_model/4-gram.bin and noticed it's (about) the same size - 3.12 GB, and I am currently downloading it.

My question is, assuming downloading the 4-gram.bin is successful, what/how can I switch the python command to read from the local file instead of the download?

Thanks!
-edmond

**Comment by edmond-toch** [comment]
So btw, I followed the instructions and did a brew install git-lfs (https://formulae.brew.sh/formula/git-lfs).

But unfortunately, I'm consistently getting the same problem (time-out connection) once the download size is about 2.0GiB =~2.147GB. 

The problem happens when I try to download the 4-gram.bin from chrome, and safari.
Though I was able to download completely using wget, because it did a "smart" resume (after it too reached a timeout when the file size was about 2.0GiB). Here's the wget output (and below is the python error when running the command
processor = AutoProcessor.from_pretrained("patrickvonplaten/wav2vec2-base-100h-with-lm") )
--------------------
Wget output:
wget https://huggingface.co/patrickvonplaten/wav2vec2-base-100h-with-lm/resolve/main/language_model/4-gram.bin
--2022-06-24 01:27:00--  https://huggingface.co/patrickvonplaten/wav2vec2-base-100h-with-lm/resolve/main/language_model/4-gram.bin
Resolving huggingface.co (huggingface.co)... 3.227.111.18, 34.197.58.156
Connecting to huggingface.co (huggingface.co)|3.227.111.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn-lfs.huggingface.co/patrickvonplaten/wav2vec2-base-100h-with-lm/e674d4a61df15bef37cd49183dc4fb087aaa3d7819d0ff8347068a880f033c61?response-content-disposition=attachment%3B%20filename%3D%224-gram.bin%22 [following]
--2022-06-24 01:27:00--  https://cdn-lfs.huggingface.co/patrickvonplaten/wav2vec2-base-100h-with-lm/e674d4a61df15bef37cd49183dc4fb087aaa3d7819d0ff8347068a880f033c61?response-content-disposition=attachment%3B%20filename%3D%224-gram.bin%22
Resolving cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)... 13.226.2.118, 13.226.2.53, 13.226.2.34, ...
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|13.226.2.118|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3124591979 (2.9G) [application/octet-stream]
Saving to: ‘4-gram.bin’

4-gram.bin              68%[=================>         ]   2.00G  --.-KB/s    in 72m 24s 

2022-06-24 02:39:25 (483 KB/s) - Read error at byte 2149217817/3124591979 (Operation timed out). Retrying.

--2022-06-24 02:39:26--  (try: 2)  https://cdn-lfs.huggingface.co/patrickvonplaten/wav2vec2-base-100h-with-lm/e674d4a61df15bef37cd49183dc4fb087aaa3d7819d0ff8347068a880f033c61?response-content-disposition=attachment%3B%20filename%3D%224-gram.bin%22
Connecting to cdn-lfs.huggingface.co (cdn-lfs.huggingface.co)|13.226.2.118|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3124591979 (2.9G), 975374162 (930M) remaining [application/octet-stream]
Saving to: ‘4-gram.bin’

4-gram.bin             100%[++++++++++++++++++========>]   2.91G  1.00MB/s    in 19m 18s 

2022-06-24 02:58:45 (823 KB/s) - ‘4-gram.bin’ saved [3124591979/3124591979]

--------------------
python error message to the command
processor = AutoProcessor.from_pretrained("patrickvonplaten/wav2vec2-base-100h-with-lm")

Downloading:  69%|██████▊   | 2.15G/3.12G [2:40:36<2:05:51, 130kB/s]Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/urllib3/response.py", line 441, in _error_catcher
    yield
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/urllib3/response.py", line 522, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/ssl.py", line 1242, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/ssl.py", line 1100, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/requests/models.py", line 760, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/urllib3/response.py", line 579, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/urllib3/response.py", line 544, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/urllib3/response.py", line 446, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/echalom/PycharmProjects/pythonProject3/wav2vec2_test2.py", line 8, in <module>
    processor = AutoProcessor.from_pretrained("patrickvonplaten/wav2vec2-base-100h-with-lm")
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/transformers/models/auto/processing_auto.py", line 223, in from_pretrained
    return processor_class.from_pretrained(
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/transformers/models/wav2vec2_with_lm/processing_wav2vec2_with_lm.py", line 156, in from_pretrained
    decoder = BeamSearchDecoderCTC.load_from_hf_hub(
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/pyctcdecode/decoder.py", line 757, in load_from_hf_hub
    cached_directory = snapshot_download(model_id, cache_dir=cache_dir, **kwargs)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/huggingface_hub/snapshot_download.py", line 235, in snapshot_download
    path = cached_download(
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 671, in cached_download
    http_get(
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/huggingface_hub/utils/_deprecation.py", line 32, in inner_f
    return f(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 436, in http_get
    for chunk in r.iter_content(chunk_size=1024):
  File "/opt/homebrew/anaconda3/envs/untitled/lib/python3.9/site-packages/requests/models.py", line 767, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Read timed out.
Downloading:  69%|██████▊   | 2.15G/3.12G [2:40:55<2:05:51, 130kB/s]

---------------
I briefly looked at the code and saw there is a resume_size in the http_get called in file_download.py but I didn't play with it yet. I'd love to know if anyone can help - if there's a file size limit from somewhere (IP provider, Mac environment variable, etc.). Alternatively if the code can "gracefully" resume automatically as the wget did, that would be great.

Any suggestions - I'd be happy to provide more details as needed.
Thanks!
